export enum BasicStat {
    Unknown = 0,
    Strength = 4,
    Stamina = 7,
    Intelect = 5,
    Spirit = 6,
    Agility = 3
}
export enum OtherStat {
    Unknown = 0,
    MeleeHitPercent = 1,
    SpellHitPercent = 2,
    MeleeCritPercent = 3,
    RangedCritPercent = 33,
    SpellCritPercent = 4,
    ParryPercent = 5,
    DodgePercent = 6,
    BlockPercent = 66,
    BlockValue = 67,
    Defense = 7,
    ArmorPenetration = 8,
    SpellPenetration = 9,
    SpellPower = 10,
    ArcaneSpellPower = 11,
    HolySpellPower = 12,
    NatureSpellPower = 13,
    ShadowSpellPower = 14,
    FireSpellPower = 144,
    FrostSpellPower = 145,
    HealingPower = 15,
    MP5 = 16,
    HP5 = 17,
    MeleeAttackPower = 18,
    RangedAttackPower = 19,
    AttackSpeed = 20
}